---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: docker
  image: plugins/docker
  settings:
    auto_tag: true
    password:
      from_secret: docker_password
    registry: registry.huefox.com
    repo: registry.huefox.com/mcapi
    username:
      from_secret: docker_username
  when:
    branch:
    - master

...
